import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@lro-ui/sidebar";
import { Toaster } from "@lro-ui/sonner";
import { AppSidebar } from "../@components/layout/sidebar.tsx/app-sidebar";
import { getServerSideEnv } from "../@lib/server-side-env";
import { ComfyUiContextProvider } from "../modules/comfy-ui/comfy-ui-context";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const wsUrl = getServerSideEnv().COMFY_WS_URL;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased min-h-dvh text-foreground`}>
        <Providers>
          <ComfyUiContextProvider wsUrl={wsUrl}>
            <Toaster />
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <div className="flex flex-col min-h-dvh h-dvh">
                  <main className="grow">{children}</main>
                </div>
              </SidebarInset>
            </SidebarProvider>
            {/* <div className="flex flex-col min-h-dvh h-dvh">
              <header className="w-full sticky top-0 z-10 bg-background h-[var(--header-height)] ">
                <Header />
              </header>
              <main className="grow">{children}</main>
            </div> */}
          </ComfyUiContextProvider>
        </Providers>
      </body>
    </html>
  );
}
